version: "3.7"

networks:
  traefik:
    external: true
  wre:
    name: wre

services:
  php-fpm:
    image: php-fpm
    build: ./
    expose:
      - 9000
    volumes:
      - ./tmp:/home/wre/tmp
      - ./public_html:/home/wre/public_html
    networks:
      - wre
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wre
      MYSQL_USER: wre
      MYSQL_PASSWORD: wre
    volumes:
      - ./.db:/var/lib/mysql
    networks:
      - wre

  nginx:
    image: nginx:1.21
    expose:
      - 80
    volumes:
      - ./nginx/wre.conf:/etc/nginx/conf.d/default.conf
      - ./public_html:/var/www
    labels:
      traefik.enable: true
      traefik.http.routers.wre.rule: Host(`wre.localdomain`)
      traefik.http.routers.wre.entrypoints: websecure
      traefik.http.routers.wre.tls.certresolver: myresolver
    depends_on:
      - php-fpm
    networks:
      - traefik
      - wre
